#! /usr/bin/env python3

from sys import argv
from urllib import request
from lxml import etree



def paserS(argv):
    url = "http://m.dict.cn/" + argv
    headers = {"User-Agent": "Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)"}
    req = request.Request(url, headers=headers)
    page = request.urlopen(req).read()
    page = page.decode("utf-8")
    page = etree.HTML(page)
    meaning = page.xpath('//*[@id="sctlist"]/li[1]/div[1]/div/div/ul/li/strong')
    print(meaning[0].text)
    phonetic = page.xpath('/html/body/div[1]/div/div[3]/span[1]/bdo')
    print('en:', phonetic[0].text)
    phonetic = page.xpath('/html/body/div[1]/div/div[3]/span[2]/bdo')
    print('us:', phonetic[0].text)

def paserM(url):

    headers = {"User-Agent": "Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)"}
    req = request.Request(url, headers=headers)
    page = request.urlopen(req).read()
    page = page.decode("utf-8")
    page = etree.HTML(page)
    meaning = page.xpath('//*[@id="sctlist"]/li[1]/div/div/div/ul/li/strong')
    if len(meaning)>=1:
        print(meaning[0].text)
if len(argv) == 2:
    paserS(argv[1])
else:
    url = "http://m.dict.cn/"
    for each in range(1,len(argv)):
        url=url+argv[each]+'%20'
    paserM(url)
